name = 'blog-theme'
license = 'MIT'
licenselink = 'https://github.com/jenboc/blog-theme/LICENSE'
description = 'Hugo Theme used for https://jensoncain.co.uk'

# Taxonomy terms
tags = ['blog']

[author]
  name = 'Jenson Cain'
  homepage = 'https://jensoncain.co.uk'
